### ISSUE TITLE
这个工程对机器的配置是什么要求？

### ISSUE THREAD

**Issue by charon-cheung** [YukunXia/Farmland-Exploration#1]
我用NUCi7运行，配置已经比较高了，但发热十分严重，gazebo勉强能打开，根本不能拖动，没法使用

**Comment by YukunXia** [comment]
需要有GPU才行。运算量最大的是velodyne simulator。这个库写的不是非常efficient，如果不能开GPU acceleration就会非常卡，这个性能瓶颈我在仿真环境上再怎么优化都没用。

而且我的理解是NUC是为移动机器人准备的吧，工况是可以直接采lidar point cloud，而不是用来跑simulation。
